### ISSUE TITLE
[Feat.]: Support sync data from OceanBase to Elastic

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/flink-connector-oceanbase#1]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
期望使用ES 的全文索引功能, 因此需要将OceanBase 数据迁移到ES

推荐什么低延时高写入的方式？最小延迟是多少？
答：Flink CDC，当前 Flink CDC 是全量去访问 CLOG 信息，然后通过用户权限控制访问者（用户）能读到的哪些表的数据信息，所以只要权限控制得当，不会有安全问题；另外一方面，这里的全量信息是：CLOG 只存在 OBserver 上，也只有一份，Flink CDC 访问 CLOG 是 rpc 交互，最终返回给客户端需要的数据，所以除了 OBserver 本身有一份日志数据之外，其他地方没有全量的信息。【使用 ES 的全文索引功能】
```

**Comment by whhe** [comment]
Users can use a source connector for Apache Flink like Flink CDC or Chunjun to collect data from OceanBase, and sink the data to ElasticSearch by Flink ElasticSearch Connector. This solution is ready to use now.
