### ISSUE TITLE
[Question]: <title>flink 1.14 能用吗？

### ISSUE THREAD

**Issue by majiajue** [oceanbase/flink-connector-oceanbase#34]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**

**Environment**

- OS Version and CPU Arch(`uname -a`):

- Component Version:

**Comment by whhe** [comment]
目前应该是不行的，在九月正式release前会验证一下，以最终的readme描述为准吧。
