### ISSUE TITLE
[Question]: 支持rowid 切分数据方案？

### ISSUE THREAD

**Issue by melin** [oceanbase/flink-connector-oceanbase#69]
### Description

参考sqoop 中，oracle 切分数据，采用rowid 切分数据，能够保证数据切分比较均匀。不需要用户去选择切分字段，ob 是否支持类似特性
https://github.com/apache/sqoop/blob/f8beae32a067d72bf9ed6e903b041ad347ca5491/src/java/org/apache/sqoop/manager/oracle/OraOopOracleQueries.java#L335C51-L335C76

**Comment by whhe** [comment]
OceanBase 企业版 Oracle 模式中的 rowid 和 Oracle 数据库中的 rowid 有一些不同，可能并不能像你说的一样去用 https://open.oceanbase.com/blog/7256524608。
