### ISSUE TITLE
[Question]: How to get detail message about abort commit

### ISSUE THREAD

**Issue by Pandas886** [oceanbase/flink-connector-oceanbase#73]
### Description

When using direct load to Oceanbase, the insert process generally does not report an error, but when committing, an abort occurs, yet there is no clear information indicating whether the data types do not correspond. How can one see the specific reason for the abort?

**Comment by whhe** [comment]
Perhaps this issue should be discussed at https://github.com/oceanbase/obkv-table-client-java, the direct loading client is maintained there.
