### ISSUE TITLE
[Question]: Is there a plan to support odp mode in flink-connector-obkv-hbase

### ISSUE THREAD

**Issue by leilinen** [oceanbase/flink-connector-oceanbase#78]
### Description

ODP(OceanBase Database Proxy) is already supported in obkv-hbase-client, but flink-connector-obkv-hbase only support urlconfig, so is there  a plan to supprot the feature?

**Comment by whhe** [comment]
Yes, we will be working on that soon.

**Comment by leilinen** [comment]
Thats very much anticipated.
